## SVM Exercise

In [3]:
# import pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

* create X, y

In [11]:
X = irisdata.drop(columns=['Class'], axis=1)
y = irisdata.Class


* import train_test_split and split data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.60, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

* import SVC from sklearn and use Polynomial kernel

In [14]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
svclassifier = SVC(kernel='poly')



* fit training data

In [15]:
sv = svclassifier.fit(X_train, y_train)

* predict X_test

In [26]:
y_prediction = svclassifier.predict(X_test)
y_prediction

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Ir

* import confusion matrix from sklearn and print values

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import plot_confusion_matrix
print(confusion_matrix(y_test,y_prediction))
print(classification_report(y_test,y_prediction))


[[26  0  0]
 [ 0 33  0]
 [ 0 14 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        26
Iris-versicolor       0.70      1.00      0.82        33
 Iris-virginica       1.00      0.55      0.71        31

       accuracy                           0.84        90
      macro avg       0.90      0.85      0.84        90
   weighted avg       0.89      0.84      0.84        90



* create SVC with rbf kernel

In [18]:
svclassifier = SVC(kernel='rbf')

* fit training data

In [19]:
svclassifier.fit(X_train, y_train)

SVC()

* predict X_test

In [20]:
y_prediction = svclassifier.predict(X_test)

* print confusion matrix

In [21]:
print(confusion_matrix(y_test,y_prediction))
print(classification_report(y_test,y_prediction))



[[26  0  0]
 [ 0 33  0]
 [ 0  6 25]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        26
Iris-versicolor       0.85      1.00      0.92        33
 Iris-virginica       1.00      0.81      0.89        31

       accuracy                           0.93        90
      macro avg       0.95      0.94      0.94        90
   weighted avg       0.94      0.93      0.93        90



* create SVC with sigmoid kernel

In [22]:
svclassifier = SVC(kernel='sigmoid')

* fit training data

In [23]:
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

* predict X_test

In [24]:
y_prediction = svclassifier.predict(X_test)

In [120]:
print(confusion_matrix(y_test,y_prediction))
print(classification_report(y_test,y_prediction))

[[26  0  0]
 [33  0  0]
 [31  0  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.29      1.00      0.45        26
Iris-versicolor       0.00      0.00      0.00        33
 Iris-virginica       0.00      0.00      0.00        31

       accuracy                           0.29        90
      macro avg       0.10      0.33      0.15        90
   weighted avg       0.08      0.29      0.13        90

/home/gyasis/anaconda3/envs/datasci/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/gyasis/anaconda3/envs/datasci/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. 

#### Q: Which kernel was the most accurate on the testing set?